### ISSUE TITLE
大佬，麻烦看下钉钉机器人推送出现的报错

### ISSUE THREAD

**Issue by Modurll** [y1ndan/genshin-impact-helper#144]
不知道是 DD_BOT_TOKEN 和 DD_BOT_SECRET 两个参数的设置有误还是其他的地方？麻烦大佬指点一下，蟹蟹！
![D727D_78KUVYJU0@1QOLYXD](https://user-images.githubusercontent.com/62495075/109529120-5c0c9400-7af0-11eb-9713-cc007266d10c.png)

**Comment by boluosaibei** [comment]
我也是这样

**Comment by ritaswc** [comment]
```
	NO.1 账号:
    #########2021-03-19#########
    🔅[天空岛]1******4
    今日奖励: 精锻用良矿 × 3
    本月累签: 2 天
    签到结果: OK
    ############################
2021-03-19T06:20:45 INFO 准备推送通知...
2021-03-19T06:20:45 INFO Server酱 🚫
2021-03-19T06:20:45 INFO Cool Push 🚫
2021-03-19T06:20:46 ERROR Bark App 😳
Expecting value: line 1 column 1 (char 0)
2021-03-19T06:20:46 INFO Telegram Bot 🚫
Traceback (most recent call last):
  File "./genshin.py", line 228, in <module>
    notify.send(status=f'成功: {success_num} | 失败: {fail_num}', msg=msg_list)
  File "/home/runner/work/genshin-impact-helper/genshin-impact-helper/notify.py", line 424, in send
    self.ddBot(app, status, msg)
  File "/home/runner/work/genshin-impact-helper/genshin-impact-helper/notify.py", line 226, in ddBot
    secret_enc = bytes(secret).encode('utf-8')
TypeError: string argument without an encoding
Error: Process completed with exit code 1.
```
