### ISSUE TITLE
TG推送功能失效

### ISSUE THREAD

**Issue by NeiL978** [y1ndan/genshin-impact-helper#165]
程式有正確的簽到，但今天的TG推送訊息卻失敗了，現在是要自行添加TG_BOT_API進Secrets了嗎?
還是沒設定的話 預設還是https://api.telegram.org?
    #########2021-03-13#########
    🔅[]3******3
    今日奖励: Mora × 5000
    本月累签: 12 天
    签到结果: OK
    ############################
2021-03-12T22:01:53 INFO 准备推送通知...
2021-03-12T22:01:53 INFO Server酱 🚫
2021-03-12T22:01:53 INFO Cool Push 🚫
2021-03-12T22:01:53 ERROR Bark App 😳
{'code': 400, 'data': None, 'message': '找不到 Key 对应的 DeviceToken, 请确保 Key 正确! Key 可在 App 端注册获得。'}
Traceback (most recent call last):
  File "./genshin-os.py", line 161, in <module>
    notify.send(status=f'成功: {success_num} | 失败: {fail_num}', msg=msg_list)
  File "/home/runner/work/genshin-impact-helper/genshin-impact-helper/notify.py", line 402, in send
    self.tgBot(app, status, msg)
  File "/home/runner/work/genshin-impact-helper/genshin-impact-helper/notify.py", line 195, in tgBot
    url = f'https://{TG_BOT_API}/bot{TG_BOT_TOKEN}/sendMessage'
UnboundLocalError: local variable 'TG_BOT_API' referenced before assignment
Error: Process completed with exit code 1.

**Comment by y1ndan** [comment]
已修复

**Comment by NeiL978** [comment]
好的 謝謝
我明天再觀察看看
