### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by Wszl** [y1ndan/genshin-impact-helper#171]
1
Traceback (most recent call last):
  File "./genshin.py", line 232, in <module>
    notify.send(status=f'成功: {success_num} | 失败: {fail_num}', msg=msg_list)
  File "/home/runner/work/genshin-impact-helper/genshin-impact-helper/notify.py", line 402, in send
    self.tgBot(app, status, msg)
  File "/home/runner/work/genshin-impact-helper/genshin-impact-helper/notify.py", line 195, in tgBot
    url = f'https://{TG_BOT_API}/bot{TG_BOT_TOKEN}/sendMessage'
UnboundLocalError: local variable 'TG_BOT_API' referenced before assignment
Error: Process completed with exit code 1.
有时候会出现这个错误

2 
并没有国际账号，但actions还是会每天跑一次国际版的脚本

**Comment by davidelectricfree** [comment]
第一个是没有定义的问题，我看作者当天已经修复了，第二个问题你把这个国际的workflow禁用不就好了？
